<!DOCTYPE html>
<html>
<head>
  <title>Menu</title>
</head>
<body>
  <h2>Menu</h2>
  <table class="table-striped">
    <thead>
      <tr>
        <th>Slug</th>
        <th>Name</th>
        <th>Type</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>s-1</td>
        <td>S1</td>
        <td>T1</td>
        <td>view</td>
      </tr>
      <tr>
        <td>s-2</td>
        <td>S2</td>
        <td>T2</td>
        <td>view</td>
      </tr>
    </tbody>
  </table>
</body>
</html>
